### ISSUE TITLE
关于文档自动生成工具的开发建议

### ISSUE THREAD

**Issue by zhouwei25** [PFCCLab/PaddleAutoProject#12]
感谢开发者对《映射文档工作》的支持，并且构思出更高效的文档自动生成工具。

作为该任务的发起者，有以下一些开发建议：

《API映射文档》是 `自动转换工具`（https://github.com/PaddlePaddle/PaConvert ）  整体项目的一个组成部分，我们开发的顺序为：`《API映射文档》-> 自动转换工具AST开发 ` 。《API映射文档》的本质是指导AST代码开发。

API映射文档本质仍是一个 **人工分析与标注** 的工作， 对于下图中的红框内容，均依赖于人工对 **API功能、参数功能** 的具体分析；对于图中的非红框内容，由于具有统一的形式，可以采取自动爬取或生成。

<img width="727" alt="infoflow 2023-03-21 19-59-14" src="https://user-images.githubusercontent.com/52485244/226599897-8a39d784-a784-4fc5-8493-f32352b1cfde.png">

由于之前在开发自动转换工具 https://github.com/PaddlePaddle/PaConvert 时，未及时跟进文档开发，因此仅可能有部分文档，可以通过自动转换工具来生成红框内容，但后续是无法生成红框内容的。

因此建议精力和目标主要放在 **非红框内容的统一格式生成** 上，类似于code-format工具。格式规范需按照以下文档来进行：

https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/model_convert/convert_from_pytorch/api_difference/pytorch_api_mapping_format_cn.md

对于 **红框内容**，无需关注自动生成功能，理论上也不会有可供自动生成的内容。

再次感谢开发者的贡献。

**Comment by Liyulingyue** [comment]
收到建议~感谢反馈~

**Comment by Liyulingyue** [comment]
建议已收到~与目前开发内容无冲突~
