### ISSUE TITLE
Paddle Example 出现 <span class="k">

### ISSUE THREAD

**Issue by sanbuphy** [PFCCLab/PaddleAutoProject#7]
![image](https://user-images.githubusercontent.com/96160062/226505862-0cafa8b6-88ca-42d8-b3ed-72c28ed39778.png)

如题

重现用url：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/scatter_cn.html

**Comment by sanbuphy** [comment]
@gouzil   请求支援

**Comment by gouzil** [comment]
> @gouzil   请求支援

先手动删除，晚上修复
